### ISSUE TITLE
Issue for saeeda

### ISSUE THREAD

**Issue by Aqeelgene** [Aqeelgene/Sprint2andProject_007#1]
Saeeda, go to the final_version.py

1. check the code first
2. At this stage there is no option to choose the build. There should be a choice of either selecting hg19 or hg38. 

@ionpaani

**Comment by ionpaani** [comment]
Hi @Aqeelgene I have made this change and it comes up with the option. Please can you test this

**Comment by Aqeelgene** [comment]
I have tested it and it works: the modification is approved!

**Comment by ionpaani** [comment]
This issue was completed.
