### ISSUE TITLE
Refactoring environment.yml file into the Variant_Bridge folder

### ISSUE THREAD

**Issue by ionpaani** [Aqeelgene/Sprint2andProject_007#11]
Hi @Azahra1214

Please can you move the environment.yml file into the Variant_Bridge folder. 

Double check that I have this information correct  - I think you would need to 

- create your personal branch
- Refactor (move) to Variant_Bridge folder
- commit and push to your origin branch
- do a pull request
- then if either @Aqeelgene or @VIV0503 can set the "base branch to develop" and "source branch  Zahra's personal branch" and check that that the information is fine and merge

************please check my reasoning for the steps is ok

**Comment by Azahra1214** [comment]
@Aqeelgene I tried to create a branch but I dont have acces rights. May be if you can add me as a collaborator please.

**Comment by Aqeelgene** [comment]
Dear Zahra, 
Salam Alaikum, 
Sorry for the delay
I have a Flu
I will add you as collaborator 

Sent from Yahoo Mail on Android 
 
  On Fri, 23 Feb 2024 at 20:44, ***@***.***> wrote:   


@Aqeelgene I tried to create a branch but I dont have acces rights. May be if you can add me as a collaborator please.

**Comment by VIV0503** [comment]
Hi everyone, I have tried to do this and you should see that the environment.yml is now in the main variant_bridge folder
