### ISSUE TITLE
requirements file / dependencies

### ISSUE THREAD

**Issue by ionpaani** [Aqeelgene/Sprint2andProject_007#14]
Hi all I want to check something
@Azahra1214  do we not need to have some sort of file with dependencies ?  Please can you advise on this? 
Saeeda

**Comment by ionpaani** [comment]
Reading this and I think we have it - https://shandou.medium.com/export-and-create-conda-environment-with-yml-5de619fe5a2

Dependencies file would be the the environment.yml file. 
Conda uses this, whilst pip uses requirements.txt. 

If we are using conda and already have the environments - do we need requirements.txt then?

**Comment by Azahra1214** [comment]
Yes .. I am creating it and will share shortly.

**Comment by Azahra1214** [comment]
[requirements.txt](https://github.com/Aqeelgene/Sprint2andProject_007/files/14410617/requirements.txt)

**Comment by Azahra1214** [comment]
@ionpaani @Aqeelgene please find the requirement.txt file for our project in above comment. and Zahra2 branch has environment.yml file. I am sending it to everyone over slack as well.
environment.yml

**Comment by Azahra1214** [comment]
To complete Project_task 2 I needed to create a requirements file. Somehow this didn't get pushed to github so I will do this.

**Comment by ionpaani** [comment]
Hey thanks!!!! I see it and I also ran this code on my Pycharm and I got it work. :)
