### ISSUE TITLE
References / resources

### ISSUE THREAD

**Issue by ionpaani** [Aqeelgene/Sprint2andProject_007#15]
Hi - Violetta had mentioned having references. Should we do have a txt file with references?

**Comment by Aqeelgene** [comment]
References:

Websites:
https://ioflood.com/blog/python-create-file/
https://www.freecodecamp.org/news/file-handling-in-python/
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
https://www.isdmsociety.org/seminars/
https://docs.python.org/3/library/venv.html
https://www.pluralsight.com/blog/software-development/the-definitive-guide-to-forks-and-branches-in-git
https://stackoverflow.com/questions/3611256/forking-vs-branching-in-github
https://www.w3schools.com/
https://stackoverflow.com/
https://stackoverflow.com/questions/25023233/how-to-save-python-screen-output-to-a-text-file
https://blog.enterprisedna.co/python-write-to-file/


Youtube videos:
https://www.youtube.com/watch?v=KkEoaPgeuCc
https://www.youtube.com/watch?app=desktop&v=ibVSPVz2LAA&pp=ygUTI3RlbGxtZXRob2RpbnB5dGhvbg%3D%3D
https://www.youtube.com/watch?v=KckAaeVob74
https://www.youtube.com/watch?v=G8vouA-L1OI
https://www.youtube.com/watch?v=tRZGeaHPoaw


Chat GPT

Learning materials of Unit 3, especially lessons 11-16

**Comment by ionpaani** [comment]
I can see Violetta has pushed the references file. I've closed this issue
