### ISSUE TITLE
Issue for Zahra - task 2 following on from Saeeda

### ISSUE THREAD

**Issue by Aqeelgene** [Aqeelgene/Sprint2andProject_007#3]
Hi Zahra, 
@ionpaani has modified the base file so that options are given. To improve this further and so that the first output is not overwritten. The code needs to be modified. Peter suggested string formatting in order to have dynamic naming.

The file from @ionpaani is called Project_task1.py

**Comment by Azahra1214** [comment]
@Aqeelgene , Me and Saeeda had a meeting today and we decided the next steps. Looking forward to your approval before we modify.

**Comment by Aqeelgene** [comment]
Hello Zahra; sorry I couldn't attend last meeting.

Looking forward to meet today Monday.

**Comment by Azahra1214** [comment]
This task is complete I have now closed this issue.
