### ISSUE TITLE
Issue for Violetta -

### ISSUE THREAD

**Issue by Aqeelgene** [Aqeelgene/Sprint2andProject_007#4]
Hello Violetta,
After Zahra has fixed the dynamic naming then there is a need to extract information from the text file and organise it in a list and save it in a text file. Whether it is the same or different it is fine as long as the information is not overwritten. 

Peter suggested the following steps:
1. loop
2. extract
3. list
4. table

These are Pete suggestion which we can read about too before completing and see which would be easier for us to continue with.

**Comment by VIV0503** [comment]
Hi Ahmad, 
I have cloned the repo and I want to do the task and I am trying to but I need some guidance please. 
Thank you
Violetta

**Comment by VIV0503** [comment]
Hi Ahmad,  I am struggling with the crashed PyCharm in UbuntuVM. I sent a message to Peter 4 days ago to inform him of my issues, but I have not heard from him. I have reinstalled the PyCharm Community version and connected GitHub via the token we created last time( when the Ubuntu VM Pycharm crashed. Today, I have asked for a meeting with him to provide more insight into the task assigned to me as part of our project. I proposed meeting with him on Monday, 26 Feb, and after our meeting today, Friday / Sat 2-24 Feb,2024.

**Comment by Aqeelgene** [comment]
I so sorry to hear about your struggling with PyCharm; I hope you'll fix it asap. Let us know about your Pycharm issue after your meeting.

**Comment by Aqeelgene** [comment]
Violetta's original task is no longer applicable. Instead, Violetta has been involved in testing, documenting, creation of the references.txt file and refactoring relevant files into the variant_bridge folder. 

In summary:

1. Logging code (Done).
2. Creation of references.txt
3. refactoring the environment.yml file
4. documentation
5. testing
